### [CVE-2019-16228](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16228)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.

### POC

#### Reference
- https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE

#### Github
No PoCs found on GitHub currently.

