### [CVE-2019-9948](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-9948)
![](https://img.shields.io/static/v1?label=Product&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=n%2Fa&color=blue)
![](https://img.shields.io/static/v1?label=Vulnerability&message=n%2Fa&color=brighgreen)

### Description

urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.

### POC

#### Reference
- http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html
- https://bugs.python.org/issue35907

#### Github
- https://github.com/revl-ca/scan-docker-image

